//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GardenerKlondike.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goal : Entity
    {
        public string Name { get; set; }
        public string Note { get; set; }
        public bool IsCompleted { get; set; }
        public string User { get; set; }
    }
}
